name: Run Full Suite of Checks and Tests

on:
  push:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Run unit tests with version ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python for test - ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Setup ffmpeg for unit tests (moviepy)
        uses: federicocarboni/setup-ffmpeg@v3.1
      
      - name: Install tox
        run: python -m pip install tox-gh>=1.2

      # - name: Setup test suite
      #   run: tox -vv --notest -e test

      - name: Setup and run test suite
        run: tox --skip-pkg-install -e test
